modLoader="javafml"
loaderVersion="[43,)"
license="MIT"
issueTrackerURL="https://github.com/kawaiicakes/Clothing/issues"

[[mods]]
modId="clothing"
version="${file.jarVersion}"
displayName="Clothing!"
displayURL="https://github.com/kawaiicakes/Clothing/"
logoFile="clothing.png"
credits="Thanks to ME!"
authors="kawaiicakes"
description='''
Epic cosmetics with custom 3D models, customization, and massive compatibility with other mods!
'''

[[dependencies.clothing]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.clothing]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
